#!/bin/sh

#  gov.gsa.adobe_flash_player.uninstall.sh
#  govgsagit

#  Created by AVB on 10042018

rm -rf "/Applications/Utilities/Adobe Flash Player Install Manager.app"
rm -rf "/Library/Application Support/Adobe/Flash Player Install Manager"
rm -rf "/Library/Internet Plug-Ins/Flash Player.plugin"
rm -rf "/Library/Internet Plug-Ins/flashplayer.xpt"
rm -rf "/Library/PreferencePanes/Flash Player.prefPane"

echo $(date) "Flash Player Has Been Uninstalled." >> /var/log/GSAlog

exit 0
