#!/bin/sh

#  gov.gsa.vlc.uninstall.sh
#  govgsagit
#
#  Created by AVB on 10/10/2018.
#  
#get current user
user=`who|grep console|sed -n 1p|awk '{print $1}'`

rm -rf /Applications/VLC.app &>/dev/null
rm -rf /Applications/GSA\ Elemental\ Files &>/dev/null
rm -rf Users/$user/Application\ Support/org.videolan.vlc &>/dev/null
rm -rf Users/$user/Saved\ Application\ State/org.videolan.vlc.savedState &>/dev/null
rm -rf Users/$user/Preferences/org.videolan.vlc.plist &>/dev/null
#
pkgutil --forget gov.gsa.gsaelementalfiles3.0.308022018 &>/dev/null
echo $(date) "VLC Uninstalled" >> /var/log/GSAlog
#
exit 0
