#!/bin/sh

#  gov.gsa.VMWare_Horizon.extattrib.sh
#  govgsagit
#
#  Created by AVB on 9/21/18.
#  
# Variables
##############################################
bddy=/usr/libexec/PlistBuddy
tgt=/Applications/VMware\ Horizon\ Client.app/Contents/Info.plist
##############################################
if [[ -e $tgt ]]; then
instld=`$bddy -c "print CFBundleShortVersionString" "$tgt"`
echo "<result>$instld</result>"
else
echo "<result>Not Installed</result>"
fi
exit 0
